### PR TITLE
Toolbox lib & provisioning command

### PR DESCRIPTION
**Pull request by sandermangel**
So, remember with Magento 2 how you have to run 6 or more commands in a specific order to make sure you have everything up and ready when starting to develop? 

Was thinking that it would be cool to have an easy command for that which switches branch, pulls it and composer installs it. Anything we might add in the future like running a database migration can go in here.

### CODE REVIEW

**Comment by andrewhowdencom** [comment]
I know work on this has been started, but Make is a good candidate for this sort of development repo hackery.

**Comment by sandermangel** [comment]
@andrewhowdencom a make file does make sense when only running the git and composer command but I would guess we'd soon add other, more framework specific, commands which would not run from a make file.
It's an interesting discussion tho. @dmanners @adam-paterson

**Comment by adam-paterson** [comment]
+1 for this. It should be contained in the framework repository when we get around to the restructure.

**Comment by dmanners** [comment]
Overall I like this sort of thing. I just would put a sage father like warning here and say this could easily explode and would love to consider active refactoring a must for this command!

**Review by dmanners — APPROVED** [review]
Love the idea, might not last the test of time but works for me for now. Get it merged!

**Pull request merged**
