### PR TITLE
#35: Removed the composer.lock + required PHP 7

### PR DESCRIPTION
**Pull request by andreasemer**
## Description

Describe your changes in detail.

## Motivation and context

Why is this change required? What problem does it solve?

If it fixes an open issue, please link to the issue here (if you write `fixes #num`
or `closes #num`, the issue will be automatically closed when the pull is accepted.)

## How has this been tested?

Please describe in detail how you tested your changes.

Include details of your testing environment, and the tests you ran to
see how your change affects other areas of the code, etc.

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

Go over all the following points, and put an `x` in all the boxes that apply.

Please, please, please, don't send your pull request until all of the boxes are ticked. Once your pull request is created, it will trigger a build on our [continuous integration](http://www.phptherightway.com/#continuous-integration) server to make sure your [tests and code style pass](https://help.github.com/articles/about-required-status-checks/).

- [x] I have read the **[CONTRIBUTING](CONTRIBUTING.md)** document.
- [x] My pull request addresses exactly one patch/feature.
- [x] I have created a branch for this patch/feature.
- [x] Each individual commit in the pull request is meaningful.
- [x] I have added tests to cover my changes.
- [x] If my change requires a change to the documentation, I have updated it accordingly.

If you're unsure about any of these, don't hesitate to ask. We're here to help!

### CODE REVIEW

**Comment by sandermangel** [comment]
@andreasemer thanks for your PR. Regarding the composer.lock, any time `$ composer install` is called (with a deploy for example) it would also look for updates without the lock in the repo. This does not seem desirable behavior

**Comment by sandermangel** [comment]
Including the PHP version in the composer.json seems like a very good idea.

**Comment by andreasemer** [comment]
@sandermangel If a lockfile is present, composer will not update any dependencies, it will just install the specified dependencies from the lockfile.

Projects like https://github.com/symfony/symfony or https://github.com/lizards-and-pumpkins/catalog are not having a lockfile, but for example https://github.com/drupal/drupal is using it.

**Comment by andreasemer** [comment]
The thing is, in a customer project it makes a lot of sense to commit a lockfile in the repo, but i think in a opensource project this is not optimal. 

What cases do we have:

**We remove the lockfile - A dependency breaks our code with a new release**
* Great, we see this in CI and can fix it
* We should specifiy the version more specific, or if its the case we should blame the devs of the dependency (ignore SemVer for example)

**We keep the lock file - A user updates the dependencies with composer**
* Users will use "composer update", even if they just want to install/change a single thing, maybe the code will break and will blame KickAss
* We don't see issues with dependencies automatically

From my point of view we should remove the lockfile. What do you thing?

**Comment by sandermangel** [comment]
While in theory I get what you're saying I think it adds a layer of complexity. We would have to fix the version numbers to prevent unwanted updates when running `$ composer install`. 
In that case we would have to manually check for updates once in a while.

To be honest NOT fixing versions in any way sounds really scary.
I vote for leaving the composer.lock in but adding the minimal PHP version.
Let's see what @adam-paterson and @dmanners say :)

**Comment by adam-paterson** [comment]
Ahhh the life old debate of commit the lock or not.

I use one simple rule which aides development speed and dependency stability.

**Always commit `composer.lock` for applications. Maybe commit `composer.lock` for components.**

This repository is the framework and so we should be keeping the lock file in version control to ensure everybody developing on the framework is using the dependancy versions we've chosen.

When we get around to extracting out the different domains into components we'll have to discuss again whether to commit the lock file or not.


I vote the `composer.lock` remains.

**Comment by adam-paterson** [comment]
@andreasemer If you can amend the commit to keep `composer.lock` we can accept the PR. The application and framework have been separated out into individual repositories. The `composer.lock` doesn't exist in that repo for the reasons above.

**Pull request closed without merging**
